language: csharp
solution: src/Nano.sln
install:
  - nuget restore src/Nano.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/Nano.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/Nano.Tests/bin/Release/Nano.Tests.dll